# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs: 
  dev-doc-build:
    docker:
      - image: ubuntu:jammy
    steps:
      - checkout
      - run:
          name: "Install the pre-requisites"
          command: |
            apt update
            apt install -y doxygen graphviz
      #- run:
      #    name: "Clone the source code"
      #    command: |
      #      apt update
      #      apt install -y git
      #      git clone https://github.com/nexoedge/nexoedge ~/project
      - run:
          name: "Build the developer doc"
          command: |
            cd ~/project
            doxygen
  user-doc-build:
    docker:
      - image: ubuntu:jammy
    steps:
      - checkout
      - run:
          name: "Install the pre-requisites"
          command: |
            apt update
            apt install -y python3-pip
            pip install sphinx_rtd_theme
      #- run:
      #    name: "Clone the source code"
      #    command: |
      #      apt update
      #      apt install -y git
      #      git clone https://github.com/nexoedge/nexoedge ~/project
      - run:
          name: "Build the user doc"
          command: |
            cd ~/project/docs/user-doc
            make html
  code-build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: ubuntu:jammy
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install the pre-requisites"
          command: |
            apt update
            apt install -y cmake git g++ libssl-dev libboost-filesystem-dev libboost-system-dev libboost-timer-dev libboost-log-dev libboost-random-dev libboost-locale-dev libboost-regex-dev autoconf libtool nasm pkg-config libevent-dev uuid-dev redis-server redis-tools libxml2-dev libcpprest-dev libaprutil1-dev libapr1-dev libglib2.0-dev libjson-c-dev unzip curl nlohmann-json3-dev libcurl-ocaml-dev libsodium-dev
      #- run:
      #    name: "Clone the source code"
      #    command: |
      #      apt update
      #      apt install -y git
      #      git clone https://github.com/nexoedge/nexoedge ~/project
      - run:
          name: "Build the system components"
          command: |
            cmake -DCMAKE_BUILD_TYPE=Release ~/project
            make package

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  check-build:
    jobs:
      - dev-doc-build
      - user-doc-build
      - code-build
